[package]
name = "schnapsen_server"
version = "0.1.0"
authors = ["Daniel Becker <daniel.93.becker@gmail.com>"]

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

schnapsen_core = { path = "../schnapsen_core" }
