[package]
name = "schnapsen"
version = "0.1.0"
authors = ["danielbecker"]

[dependencies]
rand = "0.3.16"

serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

schnapsen_core = { path = "schnapsen_core" }
schnapsen_server = { path = "schnapsen_server" }

[workspace]
